number: 223
title: Multi-User-Applikationen objektorientiert realisieren
competences:
  - - title: Projektqualität
      items:
        - title: Dokumentation und sinnvoller Einsatz von Dokumentationstools
        - title: Konventionen beachtet (Code, Dateinamen, Frameworks etc.)
        - title: Applikation ist lauffähig
        - title: Abschlusspräsentation

    - title: Domänenmodell und Architektur
      items:
        - title: Anforderungen berücksichtigt
        - title: Domänenspezifische Fachbegriffe verwendet
        - title: Implementation entspricht Dokumentation
        - title: Datenbankmodell

    - title: Multi-User-Applikation
      items:
        - title: Authentifizierung
        - title: Benutzerprofil
        - title: Benutzerverwaltung
        - title: Benutzerrollen und Berechtigungen
        - title: Aktivitätsprotokoll
        - title: Domänen-spezifische Funktionalität und Benutzerinterface (UI)
        - title: Tests

  - - title: Sozialkompetenz
      items:
        - title: "Arbeits- und Terminverhalten (Anzahl Verspätungen: %{absences_count})"

  - - title: Schriftliche Einzelprüfung (Online-Test)
      items:
        - title: Verständnisfragen
          max_points: 10.0
